# Generated by Django 4.2.7 on 2023-12-09 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newprojectapp1', '0002_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='desc',
            new_name='desg',
        ),
    ]
