# Generated by Django 4.2.7 on 2023-12-09 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newprojectapp1', '0003_rename_desc_teacher_desg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='Fullname',
            new_name='name',
        ),
    ]
